language: node_js
node_js:
- '6.9'
branches:
  only:
  - master
  - develop
env:
  global:
    secure: "TX32sXwl+6S5QaETRQ5c+hV7ryTdocjGPIjWkEFOYH5oGVPXhD4TtINRP+k6qHbNW4tZ5/l92E5Muebwl/Spp5LpkzNlHVXtKp69MF/0pPV8nTswF5Va0LNOvcbao5NStYElFL5buaRvoWJLouUczAkV1q4y3YEUgPX/Ba5iV+hjtsl5voq/AtJJ3l6PJuD1Wwt4DI1Wa6tstl5xQBiXIbacn+OhI0dXxvrOQgOUA8phzaWqOSystxyHcKIOdu1dsNs8ksSbpMQP7vs2/Uth6jZwQrHYE5vu1XnQFQD8L0htywJvXCOrfhgwaH4WXKR7lUaXFtnIXJbgCWrZfLPrpuBNVZlS0gnHZYMGrWq1fB7wrSXV57fmWcZoQTZ8ey9cxpaDLm8M4iIHiDrYSJbfHJZaFBGeZc434NRsYAqsuZ/xjsC2PgpGIQrDOjsuqlJrqS7gf46NoXD3Mz9p94eRkTKV9SjDeDiyEpMKK7BlmiUoe6JXv5DXJMP0PRbAhlpLs4Pwyilrzj0WLyYoKOukvgJ9HJbMqS6vQIPc8UcOwM1fd1cD0j+SoVs+1BDXa3jMWQ+45QOaPj/U+b9ZEL0CAyjgif/TV+9gnqbdY7uXcVG4lmQxKOxl0bxXcFD88S7NqJKMseafWKdI5ZOsD6eY6kH0YK4sGjWwfUK2zjZ8PX0="
