language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master
    - /^greenkeeper/.*$/

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod --aot

after_success:
  - firebase --non-interactive deploy --token "${FIREBASE_TOKEN}" --project "mychatapp-mf"
  
cache:
  directories:
  - node_modules
