language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod --aot

deploy:
  provider: firebase
  token:
    secure: FIREBASE_TOKEN
  project: "mychatapp"
  skip_cleanup: true
