language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master
    - develop
    - /^greenkeeper/.*$/

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  
before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod --aot

after_success:
  - firebase --non-interactive deploy --token "${FIREBASE_TOKEN}" --project "mychatapp-mf"
  
cache:
  directories:
  - node_modules
